export const GOT_BEST_SELLERS = 'GOT_BEST_SELLERS';
export const GOT_ALL_MENU_ITEMS = 'GOT_ALL_MENU_ITEMS';
export const GOT_PIZZA_MENU_ITEMS = 'GOT_PIZZA_MENU_ITEMS';
export const GOT_PASTA_MENU_ITEMS = 'GOT_PASTA_MENU_ITEMS';
export const GOT_SALAD_MENU_ITEMS = 'GOT_SALAD_MENU_ITEMS';
export const GOT_DESERT_MENU_ITEMS = 'GOT_DESERT_MENU_ITEMS';
